### ISSUE TITLE
Traits or Dependent/Required plugins what is their final goal ? 

### ISSUE THREAD

**Issue by pith** [nuun-io/project-enhancement-proposals#3]
I just though that we may have focused too much on what they (trait, dependent plugin) were instead of what they were used for.

I don't remember the difference between required and dependent so let's just call them before and after.
- A "before" trait is always used to extend/configure a plugin
- An "after" trait is always used to access data aggregated by a plugin

So I think it might be a good idea to express those concepts instead of hiding them in generic traits which could mix them.

Example:

A trait `ConfigurationTrait` could be splitted into a `ConfigurationBuilder` and a `ConfigurationHolder`.

```
public class ConfigurationTrait {
    void registerConfiguration(Configuration config);
    Configuration getConfig();
}
```

```
public class ConfigurationBuilder implements PluginBuilder {
    void registerConfiguration(Configuration config);
}
```

```
public class ConfigurationHolder implements PluginHolder {
    Configuration getConfig();
}
```

Like this the concerns will be properly splitted. And the plugins order will be obvious. 

NB: I might be wrong about the names: holder and builder. But they have to be short and easy to understand.

**Comment by ejemba** [comment]
The essence here is initializing the all the plugins alltogether or isolated

Regarding : required,dependant,before and after
The base is the following : The kernel is initializing, then starting a list of plugins in a computed order.
Before initialization take place, each plugin can ask the kernel to be initialized before or after another plugin. The order is computed before the initialisation, in function of all plugin requests. 
The actual version, is that a plugin just declare the fact it needs another plugin (require) or the fact another plugin need him (dependent) . With before , after the semantic change we are just saying we want to be before or after another plugin in the « plugin initialisation chain ».

Regarding : trait (in fact plugin trait).
We do not want make hard link between plugins so we create interfaces (trait). Order does not change here.

I hope it is clearer now. The purpose is simple here.
But I fear adding new concepts builder and holder can complicate the story more. So yes in one case we are reading from what is initialized before and in another case we write what is not already initialized, but I don't think we should explicitely name them, plugin author should name their trait/plugin the way they care. Nothing prevent plugin/trait authors to have name conventions. Nuun should not have this convention at this level.

**Comment by ejemba** [comment]
I don't think we might force plugin authors to use traits, if they want all coupled they should be able to do so. Perhaps we should not differentiate Plugins Class and Trait Interface in the API.
before()/after() returns indifferently a collection of plugin classes or trait interface
this way we cut down the number of methods. 

before() → {BarPlugin.class}
after() → {LoggingTrait.class}
then
initContext.get(LoggingTrait.class);
initContext.get(BarPlugin.class);
